plugins {
    id 'java'
    id 'io.freefair.lombok' version '9.2.0'
    id 'run.halo.plugin.devtools' version '0.8.0'
}

group = 'run.halo.mcpserver.examples'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly platform('run.halo.tools.platform:plugin:2.26.0')
    compileOnly 'run.halo.app:api'
    compileOnly 'io.projectreactor:reactor-core'
    compileOnly files('../../api/build/libs/api-1.0.0-SNAPSHOT.jar')
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

halo {
    version = '2.26'
}
